version: '3.8'

services:
    # Laravel Application dengan FrankenPHP
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: cuanku-app-prod
        restart: unless-stopped
        ports:
            - '8000:80'   # HTTP - Akses via port 8000
            - '8001:443'  # HTTPS - Akses via port 8001
        volumes:
            - ./storage:/app/storage
            - ./bootstrap/cache:/app/bootstrap/cache
            - ./.env:/app/.env:ro
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
        network_mode: bridge  # Use default bridge network for MySQL access
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost']
            interval: 30s
            timeout: 10s
            retries: 3

    # Node.js untuk Build Assets (Production)
    node-build:
        build:
            context: .
            dockerfile: Dockerfile.node
        container_name: cuanku-node-build
        volumes:
            - ./public/build:/output # Output untuk built assets
        network_mode: bridge
        profiles:
            - build
